<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Marketplace.SharedKernel\Marketplace.SharedKernel.csproj" />
    <ProjectReference Include="..\Marketplace.Infrastructure.Shared\Marketplace.Infrastructure.Shared.csproj" />
    <ProjectReference Include="..\Marketplace.Modules.Identity\Marketplace.Modules.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
